In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from glob import glob
# Aplicar configuraciones de visualización total de Pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

from pathlib import Path
import glob

import warnings
warnings.filterwarnings("ignore")
import plotly.express as px

In [15]:
df = pd.read_excel('PILOTO.xlsx')

In [16]:
print("Cese", df["Cese"].unique())
print("Departamento_1", df["Departamento_1"].unique())
print("Puesto", df["Puesto"].unique())

Cese [1 0]
Departamento_1 ['Cajas' 'Recepción' 'Sala Frescos'
 'Comidas Preparadas Panadería Y Pastelería' 'Sala' 'Administración'
 'Almacén' 'Almacén Frescos' 'Electro' 'Recepción E Inventarios'
 'Comidas Preparadas' 'Carnes/Pescadoss/Fiambres/Frutas verduras'
 'Decoración' 'E-Commerce Virtual']
Puesto ['Cajero 5X2' 'Multifuncional' 'Cajero 6X1' 'Asistente De Self Check Out'
 'Multifuncional 5X2 1Er Turno' 'Multifuncional 5X2' 'Cajero 3X4'
 'Cajero 4X3' 'Supervisor De Cajeros 5X2' 'Repres. De Servicios'
 'Jefe De Seccion' 'Gerente De Tienda' 'Trainee Subgerente De Tienda'
 'Multifuncional 5X2 Campaña' 'Supervisor De Cajeros'
 'Repres. De Servicios I' 'Vendedor' 'Especialista En Bebidas'
 'Auxiliar De Inventarios' 'Chef' 'Asistente De Tienda'
 'Subgerente De Tienda' 'Trainee Gerente De Tienda'
 'Coordinador De Operaciones Iga' 'Maestro En Panaderia' 'Jefe Entrenador'
 'Supervisor De Cajeros Pt' 'Multifuncional Peak Campaña'
 'Vendedor Part Time 5X2' 'Auxiliar Controller'
 'Asistente De Self Check Out Pt' 'Repres. De Servicios D'
 'Asistente De Merchandising' 'Coordinador De Despacho'
 'Repres. De Servicios Fds']

In [17]:
df["PuestoAgrupado"] = np.where(df["Puesto"].isin([ 'Cajas',
 'Cajero 3X4',
 'Cajero 4X3',
 'Cajero 5X2',
 'Cajero 5X2 Campaña',
 'Cajero 5X2 D',
 'Cajero 6X1',
 'Cajero 6X1 1Er Turno',
 'Cajero 6X1 2Do Turno',
 'Cajero D',]), "Caja", "Otros")

dff = df.copy()

In [18]:
dff

,Fecha inicio,Fecha,Unidad de negocio,Dirección,tienda,Departamento_1,Posición,Modalidad,Código,Género,Fecha de nacimiento,Edad,Fecha de ingreso,año,mes,periodo,Fecha de Cese,Tipo de contrato,Motivo de renuncia,TSRot,Ingresos,Cese,Head Count,Cape,Días de servicios,Tiempo de servicio,Generación,Departamento,Nombre del colaborador,Flag Incorporaciones,Flag Cese,Flag Excluir,Flag Fecha,Formato,Ubicación_2,Formato de Tienda,GOR,GOS,Sección,Puesto,Jerarquía,Años de servicio,Estado,Tipo de Cese,Formato Fin,1ra aparición,ult aparicion,# Periodos,Comparable?,ubicacion fin,Menor mayor 31,Departamento_fin,Column28,Ingresos JEQ,Cese JEQ,Head Count JEQ,Cape JEQ,PuestoAgrupado
0,2026-05-01,2026-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Cajas,Cajero 5X2,Part Time,19022849,Femenino,2003-04-10,23,2026-05-08,2026,5,202605,2026-05-11,-,Renuncia Voluntaria,De 0 Mes - 1 Mes,1,1,0,1,3,De 0 a 30 días,Generación Z - [2001-Actual],-,Perez Carpio Alessandra Johanna,1,1,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Cajas,Cajero 5X2,Operativo,0.00833,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Cajas,NaN,0.5,0.5,0.0,0.5,Caja
1,2026-05-01,2026-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Cajas,Cajero 5X2,Part Time,19011387,Femenino,2004-04-10,22,2026-03-23,2026,3,202603,2026-05-16,-,Renuncia Voluntaria,De 1 Mes - 3 Meses,0,1,0,1,54,De 31 a 60 días,Generación Z - [2001-Actual],-,Ormeño Bedoya Fiorella Maryory,0,1,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Cajas,Cajero 5X2,Operativo,0.14722,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Cajas,NaN,0.0,0.5,0.0,0.5,Caja
2,2026-04-01,2026-04-30,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Cajas,Cajero 5X2,Part Time,19004451,Femenino,2004-05-06,21,2026-02-18,2026,2,202602,2026-04-01,-,Renuncia Voluntaria,De 1 Mes - 3 Meses,0,1,0,1,42,De 31 a 60 días,Generación Z - [2001-Actual],-,Tarmeño Benito Britany Akhmin,0,1,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Cajas,Cajero 5X2,Operativo,0.11944,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Cajas,NaN,0.0,0.5,0.0,0.5,Caja
3,2026-04-01,2026-04-30,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Cajas,Cajero 5X2,Part Time,18998561,Femenino,2006-04-13,20,2026-01-27,2026,1,202601,2026-04-15,-,Renuncia Voluntaria,De 1 Mes - 3 Meses,0,1,0,1,78,De 61 a 90 días,Generación Z - [2001-Actual],-,Facundo Peña Jimena Anah,0,1,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Cajas,Cajero 5X2,Operativo,0.21667,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Cajas,NaN,0.0,0.5,0.0,0.5,Caja
4,2026-03-01,2026-03-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Cajas,Cajero 5X2,Part Time,19004451,Femenino,2004-05-06,21,2026-02-18,2026,2,202602,2026-04-01,-,Renuncia Voluntaria,De 1 Mes - 3 Meses,0,0,1,1,42,De 31 a 60 días,Generación Z - [2001-Actual],-,Tarmeño Benito Britany Akhmin,0,0,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Cajas,Cajero 5X2,Operativo,0.11944,Activos,Voluntaria,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Cajas,NaN,0.0,0.0,0.5,0.5,Caja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11750,2024-05-01,2024-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Comidas Preparadas,Jefe De Seccion,Full Time,203493,Femenino,1993-07-18,30,2020-03-11,2020,3,202003,NaT,Indeterminado,No Aplicable,Más De 1 Año,0,0,1,1,1542,Mayor a 180 días,Generación Y - [1980-2000],Operaciones - Tiendas,Michel Alinson,0,0,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Comidas Preparadas,Jefe De Seccion,Medio,4.22222,Activos,No especifica,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Comidas Preparadas,NaN,0.0,0.0,1.0,1.0,Otros
11751,2024-04-01,2024-04-30,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Comidas Preparadas,Jefe De Seccion,Full Time,203493,Femenino,1993-07-18,30,2020-03-11,2020,3,202003,NaT,Indeterminado,No Aplicable,Más De 1 Año,0,0,1,1,1511,Mayor a 180 días,Generación Y - [1980-2000],Operaciones - Tiendas,Michel Alinson,0,0,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Comidas Preparadas,Jefe De Seccion,Medio,4.13611,Activos,No especifica,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Comidas Preparadas,NaN,0.0,0.0,1.0,1.0,Otros
11752,2024-03-01,2024-03-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Comidas Preparadas,Jefe De Seccion,Full Time,6584,Masculino,1990-02-15,34,2015-08-01,2015,8,201508,NaT,Indeterminado,No Aplicable,Más De 1 Año,0,0,1,1,3165,Mayor a 180 días,Generación Y - [1980-2000],Operaciones - Tiendas,Carlos Antonio,0,0,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Comidas Preparadas,Jefe De Seccion,Medio,8.66667,Activos,No especifica,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Comidas Preparadas,NaN,0.0,0.0,1.0,1.0,Otros
11753,2024-02-01,2024-02-29,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Comidas Preparadas,Jefe De Seccion,Full Time,6584,Masculino,1990-02-15,34,2015-08-01,2015,8,201508,NaT,Indeterminado,No Aplicable,Más De 1 Año,0,0,1,1,3134,Mayor a 180 días,Generación Y - [1980-2000],Operaciones - Tiendas,Carlos Antonio,0,0,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Comidas Preparadas,Jefe De Seccion,Medio,8.57778,Activos,No especifica,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Comidas Preparadas,NaN,0.0,0.0,1.0,1.0,Otros
11754,2024-01-01,2024-01-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Comidas Preparadas,Jefe De Seccion,Full Time,6584,Masculino,1990-02-15,33,2015-08-01,2015,8,201508,NaT,Indeterminado,No Aplicable,Más De 1 Año,0,0,1,1,3105,Mayor a 180 días,Generación Y - [1980-2000],Operaciones - Tiendas,Carlos Antonio,0,0,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Comidas Preparadas,Jefe De Seccion,Medio,8.50000,Activos,No especifica,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Comidas Preparadas,NaN,0.0,0.0,1.0,1.0,Otros

In [19]:
dff["cat_edad"] = np.where(dff["Edad"]<21, 1,
                            np.where(dff["Edad"]<26, 2,
                                    np.where(dff["Edad"]<30, 3, 4)))

In [20]:
dff.head()

,Fecha inicio,Fecha,Unidad de negocio,Dirección,tienda,Departamento_1,Posición,Modalidad,Código,Género,Fecha de nacimiento,Edad,Fecha de ingreso,año,mes,periodo,Fecha de Cese,Tipo de contrato,Motivo de renuncia,TSRot,Ingresos,Cese,Head Count,Cape,Días de servicios,Tiempo de servicio,Generación,Departamento,Nombre del colaborador,Flag Incorporaciones,Flag Cese,Flag Excluir,Flag Fecha,Formato,Ubicación_2,Formato de Tienda,GOR,GOS,Sección,Puesto,Jerarquía,Años de servicio,Estado,Tipo de Cese,Formato Fin,1ra aparición,ult aparicion,# Periodos,Comparable?,ubicacion fin,Menor mayor 31,Departamento_fin,Column28,Ingresos JEQ,Cese JEQ,Head Count JEQ,Cape JEQ,PuestoAgrupado,cat_edad
0,2026-05-01,2026-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Cajas,Cajero 5X2,Part Time,19022849,Femenino,2003-04-10,23,2026-05-08,2026,5,202605,2026-05-11,-,Renuncia Voluntaria,De 0 Mes - 1 Mes,1,1,0,1,3,De 0 a 30 días,Generación Z - [2001-Actual],-,Perez Carpio Alessandra Johanna,1,1,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Cajas,Cajero 5X2,Operativo,0.00833,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Cajas,NaN,0.5,0.5,0.0,0.5,Caja,2
1,2026-05-01,2026-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Cajas,Cajero 5X2,Part Time,19011387,Femenino,2004-04-10,22,2026-03-23,2026,3,202603,2026-05-16,-,Renuncia Voluntaria,De 1 Mes - 3 Meses,0,1,0,1,54,De 31 a 60 días,Generación Z - [2001-Actual],-,Ormeño Bedoya Fiorella Maryory,0,1,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Cajas,Cajero 5X2,Operativo,0.14722,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Cajas,NaN,0.0,0.5,0.0,0.5,Caja,2
2,2026-04-01,2026-04-30,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Cajas,Cajero 5X2,Part Time,19004451,Femenino,2004-05-06,21,2026-02-18,2026,2,202602,2026-04-01,-,Renuncia Voluntaria,De 1 Mes - 3 Meses,0,1,0,1,42,De 31 a 60 días,Generación Z - [2001-Actual],-,Tarmeño Benito Britany Akhmin,0,1,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Cajas,Cajero 5X2,Operativo,0.11944,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Cajas,NaN,0.0,0.5,0.0,0.5,Caja,2
3,2026-04-01,2026-04-30,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Cajas,Cajero 5X2,Part Time,18998561,Femenino,2006-04-13,20,2026-01-27,2026,1,202601,2026-04-15,-,Renuncia Voluntaria,De 1 Mes - 3 Meses,0,1,0,1,78,De 61 a 90 días,Generación Z - [2001-Actual],-,Facundo Peña Jimena Anah,0,1,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Cajas,Cajero 5X2,Operativo,0.21667,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Cajas,NaN,0.0,0.5,0.0,0.5,Caja,1
4,2026-03-01,2026-03-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Viv Monterrico,Cajas,Cajero 5X2,Part Time,19004451,Femenino,2004-05-06,21,2026-02-18,2026,2,202602,2026-04-01,-,Renuncia Voluntaria,De 1 Mes - 3 Meses,0,0,1,1,42,De 31 a 60 días,Generación Z - [2001-Actual],-,Tarmeño Benito Britany Akhmin,0,0,0,1,Vivanda,Lima,Vivanda,Mali Rojas,Mali Rojas,Cajas,Cajero 5X2,Operativo,0.11944,Activos,Voluntaria,Plaza vea& Viv,2018-01-01,2026-05-01,101,Si,Viv Monterrico,#ERROR,Cajas,NaN,0.0,0.0,0.5,0.5,Caja,2

In [29]:



dff[["Modalidad", "tienda", "Código", "Género", "Fecha de ingreso", "Fecha de Cese", "Ubicación_2", "Fecha de nacimiento"]].drop_duplicates()

,Modalidad,tienda,Código,Género,Fecha de ingreso,Fecha de Cese,Ubicación_2,Fecha de nacimiento
0,Part Time,Viv Monterrico,19022849,Femenino,2026-05-08,2026-05-11,Lima,2003-04-10
1,Part Time,Viv Monterrico,19011387,Femenino,2026-03-23,2026-05-16,Lima,2004-04-10
2,Part Time,Viv Monterrico,19004451,Femenino,2026-02-18,2026-04-01,Lima,2004-05-06
3,Part Time,Viv Monterrico,18998561,Femenino,2026-01-27,2026-04-15,Lima,2006-04-13
5,Part Time,Viv Monterrico,19004449,Femenino,2026-02-18,2026-03-01,Lima,1996-05-02
...,...,...,...,...,...,...,...,...
11701,Part Time,Viv Monterrico,16252273,Femenino,2024-07-17,NaT,Lima,2003-05-04
11710,Part Time,Viv Monterrico,13816916,Masculino,2024-01-12,NaT,Lima,2003-06-03
11723,Part Time,Viv Monterrico,13599443,Masculino,2024-03-01,NaT,Lima,2004-11-16
11728,Part Time,Viv Monterrico,14230758,Masculino,2024-02-16,NaT,Lima,2002-09-20
11752,Full Time,Viv Monterrico,6584,Masculino,2015-08-01,NaT,Lima,1990-02-15

In [24]:


dff["Fecha inicio"] = pd.to_datetime(dff["Fecha inicio"])
dff["Fecha de ingreso"] = pd.to_datetime(dff["Fecha de ingreso"])
dff["Fecha de Cese"] = pd.to_datetime(dff["Fecha de Cese"])

dff["periodo_snapshot"] = dff["Fecha inicio"].dt.strftime("%Y%m")
dff["periodo_ingreso"] = dff["Fecha de ingreso"].dt.strftime("%Y%m")
dff["flag_periodo_ingreso"] = np.where(dff["periodo_snapshot"]==dff["periodo_ingreso"], 1, 0)

In [26]:
dff["Fecha inicio"] = pd.to_datetime(dff["Fecha inicio"] , errors="coerce")
dff["Fecha de ingreso"] = pd.to_datetime(dff["Fecha de ingreso"], errors="coerce")
dff["Fecha de Cese"] = pd.to_datetime(dff["Fecha de Cese"], errors="coerce")
dff["antiguedad_dias"] = (
    dff["Fecha de Cese"] - dff["Fecha de ingreso"]
).dt.days.astype("Int64")

In [28]:
dff.to_excel("piloto2.xlsx", index=False)

In [271]:


df["Fecha inicio"] = pd.to_datetime(df["Fecha inicio"] , errors="coerce")
df["Fecha de ingreso"] = pd.to_datetime(df["Fecha de ingreso"], errors="coerce")
df["Fecha de Cese"] = pd.to_datetime(df["Fecha de Cese"], errors="coerce")
df["antiguedad_dias"] = ( (df["Fecha de Cese"] - df["Fecha de ingreso"]).dt.days.astype(int))
# dff1 = dff.groupby("Fecha inicio").agg(Cese = ("Cese","sum"), Cape = ("Cape", "sum")).reset_index()
# dff1["RatioCese"] = dff1["Cese"] / dff1["Cape"]*100

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [255]:
df["antiguedad_dias"].max()

np.int64(45563)

In [225]:
dff1 = dff.copy()

In [226]:
dff1["target"] = np.where((dff1["Tipo de Cese"]=="Voluntaria")&(dff1["Cese"]==1), 1,0)

In [227]:
dic_puesto = {
    "Asistente De Self Check Out Pt": "SCO",
    "Cajas": "Cajero",
    "Cajero 5X2": "Cajero",
    "Cajero 6X1": "Cajero",
    "Cajero 3X4": "Cajero",
    "Cajero 4X3": "Cajero",
    "Cajero 5X2 Campaña": "Cajero",
    "Cajero 5X2 D": "Cajero",
    "Cajero D": "Cajero",
    "Cajero 6X1 2Do Turno": "Cajero",
    "Cajero 6X1 1Er Turno": "Cajero",
    "Jefe De Seccion": "Jefe Supervisor",
    "Trainee Jefe De Seccion": "Jefe Supervisor",
    "Multifuncional": "Multifuncional",
    "Multifuncional 5X2 Campaña": "Multifuncional",
    "Multifuncional 5X2 1Er Turno": "Multifuncional",
    "Multifuncional 5X2": "Multifuncional",
    "Multifuncional 5X2 2Do Turno Extraordinario": "Multifuncional",
    "Multifuncional 5X2 1Er Turno Extraordinario": "Multifuncional",
    "Multifuncional 5X2 Extraordinario": "Multifuncional",
    "Repres. De Servicios": "RS",
    "Repres. De Servicios D": "RS",
    "Asistente De Self Check Out": "SCO",
    "Supervisor De Cajeros": "Jefe Supervisor",
    "Supervisor De Cajeros 5X2": "Jefe Supervisor",
    "Supervisor De Cajeros Pt": "Jefe Supervisor",
    "Supervisor De Cajeros Extraordinario": "Jefe Supervisor"
}
dff1["PuestoAgrupado"] = dff1["Puesto"].map(dic_puesto)
dff1.groupby("PuestoAgrupado").size().sort_values(ascending=False).reset_index()

    PuestoAgrupado       0
0           Cajero  102732
1  Jefe Supervisor   10525
2               RS    7684
3   Multifuncional    3077
4              SCO    2927

In [228]:
dic_tienda = {
    "Pvea Acho": "Acho - PVH",
    "Pvea Alfonso Ugarte": "Alfonso Ugarte - PVH",
    "Pvea Arequipa": "Arequipa - PVH",
    "Pvea Ate": "Ate - PVH",
    "Pvea Aventura Sjl": "Aventura SJL - PVH",
    "Pvea Barranca": "Barranca - PVH",
    "Pvea Bolichera": "Bolichera - PVH",
    "Pvea Brasil": "Brasil - PVH",
    "Pvea Breña Centenario": "Brena - PVH",
    "Pvea Cajamarca": "Cajamarca - PVH",
    "Pvea Callao": "Callao - PVH",
    "Pvea Centro Civico": "Centro Civico - PVH",
    "Pvea Ceres": "Ceres - PVH",
    "Pvea Chiclayo": "Chiclayo - PVH",
    "Pvea Chiclayo Mall": "Chiclayo Aventura - PVH",
    "Pvea Chimbote": "Chimbote - PVH",
    "Pvea Chincha": "Chincha - PVH",
    "Pvea Chosica": "Chosica - PVH",
    "Pvea Colonial": "Colonial - PVH",
    "Pvea Comas": "Comas - PVH",
    "Pvea Cortijo": "Cortijo - PVH",
    "Pvea Cuzco San Antonio": "Cusco Mall - PVH",
    "Pvea El Agustino": "El Agustino - PVH",
    "Pvea El Chacarero": "El Chacarero - PVH",
    "Pvea El Ejercito": "El Ejercito - PVS",
    "Pvea Guardia Civil": "Guardia Civil - PVH",
    "Pvea Higuereta": "Higuereta - PVH",
    "Pvea Huacho": "Huacho - PVH",
    "Pvea Huancayo": "Huancayo - PVH",
    "Pvea Huaral": "Huaral - PVH",
    "Pvea Ica": "Ica - PVH",
    "Pvea Ilo": "Ilo - PVH",
    "Pvea Izaguirre": "Izaguirre - PVH",
    "Pvea Jockey Plaza": "Jockey Plaza - PVH",
    "Pvea Juliaca": "Juliaca - PVH",
    "Pvea La Curva": "La Curva - PVH",
    "Pvea La Molina": "La Molina - PVH",
    "Pvea La Placita": "Ves Placita - PVH",
    "Pvea Los Olivos": "Los Olivos - PVH",
    "Pvea Lurin": "LurIn - PVH",
    "Pvea Miraflores": "Miraflores - PVH",
    "Pvea Moquegua": "Moquegua - PVH",
    "Pvea Nuevo Chimbote": "Nvo Chimbote - PVH",
    "Pvea Paita": "Paita - PVH",
    "Pvea Pisco": "Pisco - PVH",
    "Pvea Piura": "Piura - PVH",
    "Pvea Primavera": "Primavera - PVH",
    "Pvea Pro": "Pro - PVH",
    "Pvea Puente Piedra": "Puente Piedra - PVH",
    "Pvea Puno": "Puno - PVH",
    "Pvea Puruchuco": "Puruchuco - PVH",
    "Pvea Rimac": "Rimac Alcazar - PVH",
    "Pvea Risso": "Risso - PVH",
    "Pvea Salaverry": "Salaverry - PVH",
    "Pvea San Borja": "San Borja - PVH",
    "Pvea San Isidro": "San Isidro - PVH",
    "Pvea Santa Clara": "Santa Clara - PVH",
    "Pvea Sj Lurigancho": "SJ Lurigancho - PVH",
    "Pvea Sjb Ayacucho": "SJB Ayacucho - PVH",
    "Pvea Sucre": "Sucre - PVH",
    "Pvea Sullana": "Sullana - PVH",
    "Pvea Tacna": "Tacna - PVH",
    "Pvea Talara": "Talara - PVH",
    "Pvea Talara Mall": "Talara Municipalidad - PVH",
    "Pvea Trujillo": "Trujillo - PVH",
    "Pvea Tumbes": "Tumbes - PVH",
    "Pvea Universitaria": "Universitaria - PVH",
    "Pvea Ventanilla": "Ventanilla - PVH",
    "Pvo Huanuco": "Huanuco - PVO",
    "Pvo Jaen": "Jaen - PVO",
    "Pvo Pucallpa": "Pucallpa - PVO",
    "Pvo Tarapoto": "PVEA Tarapoto",
    "Svea Alameda Sur": "Alameda Sur - PVS",
    "Svea Ayacucho": "Ayacucho - PVS",
    "Svea Caminos Del Inca": "Caminos del Inca - PVS",
    "Svea Centro Trujillo": "Centro Trujillo - PVE",
    "Svea Chaclacayo": "Chaclacayo - PVS",
    "Svea Chorrillos Iglesias": "Chorrillos Iglesias - PVS",
    "Svea Corpac": "Corpac - PVS",
    "Svea Cuzco Quoyllur": "Cusco Wanchaq-PVH",
    "Svea Dasso": "Dasso - PVS",
    "Svea El Tambo": "El Tambo Huancayo - PVS",
    "Svea Grifo Kio": "Grifo Kio - PVS",
    "Svea Grifo Mexico": "Grifo Mexico - PVH",
    "Svea Mercaderes": "Mercaderes - PVS",
    "Svea Salamanca": "Salamanca - PVS",
    "Svea San Jorge": "San Jorge - PVS",
    "Svea San Miguel": "San Miguel - PVH",
    "Svea Trujillo Mansiche": "Trujillo Mansiche - PVS",
    "Svea Trujillo Valcarcel": "Trujillo Valcarcel - PVS",
    "Svea Valle Hermoso": "Valle Hermoso - PVH",
    "Svea Villa El Salvador": "Villa el Salvador - PVS",
    "Tarapoto 2": "Tarapoto 2 - PVO",
    "Viv Asia": "Asia - VIV",
    "Viv Benavides": "Benavides - VIV",
    "Viv Dos De Mayo": "Dos de Mayo - VIV",
    "Viv Javier Prado": "Javier Prado - VIV",
    "Viv Libertadores": "Libertadores - VIV",
    "Viv Monterrico": "Monterrico - VIV",
    "Viv Pardo": "Pardo - VIV",
    "Viv Pezet": "Pezet - VIV"
}

dff1["tienda2"] = dff1["tienda"].map(dic_tienda)
dff1["Antiguedad"] = dff1["Días de servicios"]

In [229]:
df_local = pd.read_csv(
    "dimlocal.csv",
    sep="\t",
    encoding="cp1252"
)

In [230]:
dff2 = dff1.merge(df_local[["tienda2", "Ubicacion", "Cluster NSE", "formato"]], on="tienda2", how="left")

In [231]:
dff2.head(3)

,Fecha inicio,Fecha,Unidad de negocio,Dirección,tienda,Departamento_1,Posición,Modalidad,Código,Género,Fecha de nacimiento,Edad,Fecha de ingreso,Fecha de Cese,Tipo de contrato,Motivo de renuncia,TSRot,Ingresos,Cese,Head Count,Cape,Días de servicios,Tiempo de servicio,Generación,Departamento,Nombre del colaborador,Flag Incorporaciones,Flag Cese,Flag Excluir,Flag Fecha,Formato,Ubicación_2,Formato de Tienda,GOR,GOS,Sección,Puesto,Jerarquía,Años de servicio,Estado,Tipo de Cese,Formato Fin,1ra aparición,ult aparicion,# Periodos,Comparable?,ubicacion fin,Menor mayor 31,Departamento_fin,Column28,Ingresos JEQ,Cese JEQ,Head Count JEQ,Cape JEQ,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,target,PuestoAgrupado,tienda2,Antiguedad,Ubicacion,Cluster NSE,formato
0,2026-05-01,2026-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Pvea Rimac,Cajas,Cajero 5X2,Part Time,19019830,Femenino,2005-11-13 00:00:00,20,2026-04-22 00:00:00,2026-05-01,-,Renuncia Voluntaria,De 0 Mes - 1 Mes,0,1,0,1,9,De 0 a 30 días,Generación Z - [2001-Actual],-,Lopez Acuña Noemi Esther,0,1,0,1,Plaza Vea,Lima,Hiper,Vik Enciso,Sebastian Santangelo,Cajas,Cajero 5X2,Operativo,0.025,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01 00:00:00,2026-05-01 00:00:00,101,Si,Pvea Rimac,#ERROR,Cajas,NaN,0,0.5,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Cajero,Rimac Alcazar - PVH,9,Lima + Callao,B,PLAZA VEA
1,2026-05-01,2026-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Pvea Guardia Civil,Cajas,Cajero 5X2,Part Time,19019534,Femenino,2005-02-20 00:00:00,21,2026-04-22 00:00:00,2026-05-01,-,Renuncia Voluntaria,De 0 Mes - 1 Mes,0,1,0,1,9,De 0 a 30 días,Generación Z - [2001-Actual],-,Camasca Soncco Gayle Del Pilar,0,1,0,1,Plaza Vea,Lima,Hiper,Rodolfo Olivry,Sebastian Santangelo,Cajas,Cajero 5X2,Operativo,0.025,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01 00:00:00,2026-05-01 00:00:00,101,Si,Pvea Guardia Civil,#ERROR,Cajas,NaN,0,0.5,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Cajero,Guardia Civil - PVH,9,Lima + Callao,B,PLAZA VEA
2,2026-05-01,2026-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Pvea Puruchuco,Cajas,Cajero 5X2,Part Time,19019510,Femenino,2006-01-18 00:00:00,20,2026-04-22 00:00:00,2026-05-04,-,Renuncia Voluntaria,De 0 Mes - 1 Mes,0,1,0,1,12,De 0 a 30 días,Generación Z - [2001-Actual],-,Espiritu Cavana Harumy Nelly,0,1,0,1,Plaza Vea,Lima,Hiper,Rodolfo Olivry,Sebastian Santangelo,Cajas,Cajero 5X2,Operativo,0.03333,Cesados,Voluntaria,Plaza vea& Viv,2019-09-01 00:00:00,2026-05-01 00:00:00,81,Si,Pvea Puruchuco,#ERROR,Cajas,NaN,0,0.5,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Cajero,Puruchuco - PVH,12,Lima + Callao,B,PLAZA VEA

In [232]:


dff3 = dff2.copy()

In [233]:
dfxxx = dff3.groupby("Ubicacion").agg(target = ("target","sum"), total = ("target","count")).reset_index()
dfxxx["ratio"] = dfxxx["target"] / dfxxx["total"]
dfxxx
dff3["cat_ubicacion"] = np.where(dff3["Ubicacion"].isin(["Lima + Callao"]), 1, 0)

In [234]:
dfxxx = dff3.groupby("Cluster NSE").agg(target = ("target","sum"), total = ("target","count")).reset_index()
dfxxx["ratio"] = dfxxx["target"] / dfxxx["total"]
dfxxx.sort_values(by="ratio", ascending=False)

dff3["cat_cluster"] = np.where(dff3["Cluster NSE"].isin(["A"]), 1, 
                               np.where(dff3["Cluster NSE"].isin(["V"]), 2,
                                        np.where(dff3["Cluster NSE"].isin(["B"]), 3,4)))

In [235]:
dfxxx = dff3.groupby("formato").agg(target = ("target","sum"), total = ("target","count")).reset_index()
dfxxx["ratio"] = dfxxx["target"] / dfxxx["total"]
dfxxx.sort_values(by="ratio", ascending=False)

             formato  target   total     ratio
2    PLAZA VEA SUPER     477   12082  0.039480
3            VIVANDA     310    8292  0.037385
0          PLAZA VEA    3489  106569  0.032739
1  PLAZA VEA EXPRESS       0       2  0.000000

In [236]:
dfxxx = dff3.groupby("Modalidad").agg(target = ("target","sum"), total = ("target","count")).reset_index()
dfxxx["ratio"] = dfxxx["target"] / dfxxx["total"]
dfxxx.sort_values(by="ratio", ascending=False)
dff3["cat_modalidad"] = np.where(dff3["Modalidad"].isin(["Part Time"]), 1, 0)

In [237]:
dfxxx = dff3.groupby("Género").agg(target = ("target","sum"), total = ("target","count")).reset_index()
dfxxx["ratio"] = dfxxx["target"] / dfxxx["total"]
dfxxx.sort_values(by="ratio", ascending=False)

dff3["cat_genero"] = np.where(dff3["Género"].isin(["Masculino"]), 1, 0)

In [238]:
dfxxx = dff3.groupby("Tiempo de servicio").agg(target = ("target","sum"), total = ("target","count")).reset_index()
dfxxx["ratio"] = dfxxx["target"] / dfxxx["total"]
dfxxx.sort_values(by="ratio", ascending=False)

dff3["cat_tiempo_servicio"] = np.where(dff3["Tiempo de servicio"].isin(["De 0 a 30 días"]), 1, 
                                       np.where(dff3["Tiempo de servicio"].isin(["De 31 a 60 días"]), 2,
                                                np.where(dff3["Tiempo de servicio"].isin(["De 61 a 90 días"]), 3, 
                                                         np.where(dff3["Tiempo de servicio"].isin(["De 91 a 180 días"]), 4, 5))))

In [239]:
dfxxx = dff3.groupby("Edad").agg(target = ("target","sum"), total = ("target","count")).reset_index()
dfxxx["ratio"] = dfxxx["target"] / dfxxx["total"]
dfxxx.sort_values(by="ratio", ascending=False)

dff3["cat_edad"] = np.where(dff3["Edad"]<21, 1,
                            np.where(dff3["Edad"]<26, 2,
                                    np.where(dff3["Edad"]<30, 3, 4)))

In [240]:
dfxxx = dff3.groupby("PuestoAgrupado").agg(target = ("target","sum"), total = ("target","count")).reset_index()
dfxxx["ratio"] = dfxxx["target"] / dfxxx["total"]
dfxxx.sort_values(by="ratio", ascending=False)

    PuestoAgrupado  target   total     ratio
2   Multifuncional     190    3077  0.061748
4              SCO     176    2927  0.060130
3               RS     361    7684  0.046981
0           Cajero    3346  102732  0.032570
1  Jefe Supervisor     203   10525  0.019287

In [241]:
onehot = pd.get_dummies(
    dff3["formato"],
    prefix="formato",drop_first=True,
    dtype=int
)

dff3 = pd.concat([dff3, onehot], axis=1)

In [242]:
dff3.columns

Index(['Fecha inicio', 'Fecha', 'Unidad de negocio', 'Dirección', 'tienda',
       'Departamento_1', 'Posición', 'Modalidad', 'Código', 'Género',
       'Fecha de nacimiento', 'Edad', 'Fecha de ingreso', 'Fecha de Cese',
       'Tipo de contrato', 'Motivo de renuncia', 'TSRot', 'Ingresos', 'Cese',
       'Head Count', 'Cape', 'Días de servicios', 'Tiempo de servicio',
       'Generación', 'Departamento', 'Nombre del colaborador',
       'Flag Incorporaciones', 'Flag Cese', 'Flag Excluir', 'Flag Fecha',
       'Formato', 'Ubicación_2', 'Formato de Tienda', 'GOR', 'GOS', 'Sección',
       'Puesto', 'Jerarquía', 'Años de servicio', 'Estado', 'Tipo de Cese',
       'Formato Fin', '1ra aparición', 'ult aparicion', '# Periodos',
       'Comparable?', 'ubicacion fin', 'Menor mayor 31', 'Departamento_fin',
       'Column28', 'Ingresos JEQ', 'Cese JEQ', 'Head Count JEQ', 'Cape JEQ',
       'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57',
       'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61',
       'Unnamed: 62', 'Unnamed: 63', 'target', 'PuestoAgrupado', 'tienda2',
       'Antiguedad', 'Ubicacion', 'Cluster NSE', 'formato', 'cat_ubicacion',
       'cat_cluster', 'cat_modalidad', 'cat_genero', 'cat_tiempo_servicio',
       'cat_edad', 'formato_PLAZA VEA EXPRESS', 'formato_PLAZA VEA SUPER',
       'formato_VIVANDA'],
      dtype='object')

In [243]:
dff3["Antiguedad_meses"] = dff3["Antiguedad"] / 30

In [244]:
dff3["Fecha inicio"] = pd.to_datetime(dff3["Fecha inicio"])
dff3["Fecha de ingreso"] = pd.to_datetime(dff3["Fecha de ingreso"])
dff3["Fecha de Cese"] = pd.to_datetime(dff3["Fecha de Cese"])

dff3["periodo_snapshot"] = dff3["Fecha inicio"].dt.strftime("%Y%m")
dff3["periodo_ingreso"] = dff3["Fecha de ingreso"].dt.strftime("%Y%m")
dff3["flag_periodo_ingreso"] = np.where(dff3["periodo_snapshot"]==dff3["periodo_ingreso"], 1, 0)
dff3["antiguedad_dias"] = ( (dff3["Fecha de Cese"] - dff3["Fecha de ingreso"]).dt.days.fillna(9999) .astype(int))
dff3["target_ff"] = np.where(dff3["antiguedad_dias"]<=180, 1, 0)
dff4 = dff3[(dff3["flag_periodo_ingreso"]==1)]

In [246]:
dff4

,Fecha inicio,Fecha,Unidad de negocio,Dirección,tienda,Departamento_1,Posición,Modalidad,Código,Género,Fecha de nacimiento,Edad,Fecha de ingreso,Fecha de Cese,Tipo de contrato,Motivo de renuncia,TSRot,Ingresos,Cese,Head Count,Cape,Días de servicios,Tiempo de servicio,Generación,Departamento,Nombre del colaborador,Flag Incorporaciones,Flag Cese,Flag Excluir,Flag Fecha,Formato,Ubicación_2,Formato de Tienda,GOR,GOS,Sección,Puesto,Jerarquía,Años de servicio,Estado,Tipo de Cese,Formato Fin,1ra aparición,ult aparicion,# Periodos,Comparable?,ubicacion fin,Menor mayor 31,Departamento_fin,Column28,Ingresos JEQ,Cese JEQ,Head Count JEQ,Cape JEQ,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,target,PuestoAgrupado,tienda2,Antiguedad,Ubicacion,Cluster NSE,formato,cat_ubicacion,cat_cluster,cat_modalidad,cat_genero,cat_tiempo_servicio,cat_edad,formato_PLAZA VEA EXPRESS,formato_PLAZA VEA SUPER,formato_VIVANDA,Antiguedad_meses,periodo_snapshot,periodo_ingreso,flag_periodo_ingreso,antiguedad_dias,target_ff
354,2026-05-01,2026-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Pvea Puente Piedra,Cajas,Cajero 5X2,Part Time,19023084,Femenino,2006-07-29 00:00:00,19,2026-05-08,2026-05-11,-,Renuncia Voluntaria,De 0 Mes - 1 Mes,1,1,0,1,3,De 0 a 30 días,Generación Z - [2001-Actual],-,Quijano Maza Camila Alexandra,1,1,0,1,Plaza Vea,Lima,Hiper,Vik Enciso,Sebastian Santangelo,Cajas,Cajero 5X2,Operativo,0.00833,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01 00:00:00,2026-05-01 00:00:00,101,Si,Pvea Puente Piedra,#ERROR,Cajas,NaN,0.5,0.5,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Cajero,Puente Piedra - PVH,3,Lima + Callao,C,PLAZA VEA,1,4,1,0,1,1,0,0,0,0.100000,202605,202605,1,3,1
355,2026-05-01,2026-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Pvea Izaguirre,Cajas,Cajero 5X2,Part Time,19022929,Masculino,2008-01-09 00:00:00,18,2026-05-08,2026-06-01,-,Renuncia Voluntaria,De 0 Mes - 1 Mes,1,0,1,1,24,De 0 a 30 días,Generación Z - [2001-Actual],-,Sanchez Rivas Haziel Jalissat,1,0,0,1,Plaza Vea,Lima,Hiper,Vik Enciso,Sebastian Santangelo,Cajas,Cajero 5X2,Operativo,0.06389,Activos,Voluntaria,Plaza vea& Viv,2018-01-01 00:00:00,2026-05-01 00:00:00,101,Si,Pvea Izaguirre,#ERROR,Cajas,NaN,0.5,0,0.5,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Cajero,Izaguirre - PVH,24,Lima + Callao,C,PLAZA VEA,1,4,1,1,1,1,0,0,0,0.800000,202605,202605,1,24,1
356,2026-05-01,2026-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Pvea Ventanilla,Cajas,Cajero 5X2,Part Time,19022874,Femenino,2002-10-22 00:00:00,23,2026-05-08,2026-05-14,-,Renuncia Voluntaria,De 0 Mes - 1 Mes,1,1,0,1,6,De 0 a 30 días,Generación Z - [2001-Actual],-,Cari Livisi Jannide Lizbeth,1,1,0,1,Plaza Vea,Lima,Hiper,Vik Enciso,Sebastian Santangelo,Cajas,Cajero 5X2,Operativo,0.01667,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01 00:00:00,2026-05-01 00:00:00,101,Si,Pvea Ventanilla,#ERROR,Cajas,NaN,0.5,0.5,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Cajero,Ventanilla - PVH,6,Lima + Callao,C,PLAZA VEA,1,4,1,0,1,2,0,0,0,0.200000,202605,202605,1,6,1
357,2026-05-01,2026-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Pvea Cortijo,Cajas,Cajero 5X2,Part Time,19022682,Femenino,2007-02-03 00:00:00,19,2026-05-07,2026-05-19,-,Renuncia Voluntaria,De 0 Mes - 1 Mes,1,1,0,1,12,De 0 a 30 días,Generación Z - [2001-Actual],-,Minalla Bustamante Adriana Zafiro,1,1,0,1,Plaza Vea,Lima,Hiper,Johanna Vilca,Sebastian Santangelo,Cajas,Cajero 5X2,Operativo,0.03333,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01 00:00:00,2026-05-01 00:00:00,101,Si,Pvea Cortijo,#ERROR,Cajas,NaN,0.5,0.5,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Cajero,Cortijo - PVH,12,Lima + Callao,A,PLAZA VEA,1,1,1,0,1,1,0,0,0,0.400000,202605,202605,1,12,1
358,2026-05-01,2026-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Pvea Izaguirre,Cajas,Cajero 5X2,Part Time,19022541,Femenino,2006-01-22 00:00:00,20,2026-05-06,2026-05-12,-,Renuncia Voluntaria,De 0 Mes - 1 Mes,1,1,0,1,6,De 0 a 30 días,Generación Z - [2001-Actual],-,Chumpitaz Echevarria Luz Clara,1,1,0,1,Plaza Vea,Lima,Hiper,Vik Enciso,Sebastian Santangelo,Cajas,Cajero 5X2,Operativo,0.01667,Cesados,Voluntaria,Plaza vea& Viv,2018-01-01 00:00:00,2026-05-01 00:00:00,101,Si,Pvea Izaguirre,#ERROR,Cajas,NaN,0.5,0.5,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Cajero,Izaguirre - PVH,6,Lima + Callao,C,PLAZA VEA,1,4,1,0,1,1,0,0,0,0.200000,202605,202605,1,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125610,2024-05-01,2024-05-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Pvea Breña Centenario,Cajas,Supervisor De Cajeros,Full Time,9751404,Femenino,2003-03-14 00:00:00,21,2024-05-01,NaT,Indeterminado,No Aplicable,De 0 Mes - 1 Mes,1,0,1,1,30,De 0 a 30 días,Generación Z - [2001-Actual],Operaciones - Tiendas,Calderón Cortez,Naomi Violeta,1,0,0,1,Plaza Vea,Lima,Hiper,Vik Enciso,Sebastian Santangelo,Cajas,Supervisor De Cajeros,Medio,0.08333,Activos,No especifica,Plaza vea& Viv,2018-01-01 00:00:00,2026-05-01 00:00:00,101,Si,Pvea Breña Centenario,#ERROR,Cajas,NaN,1,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Cajero,Brena - PVH,30,Lima + Callao,B,PLAZA VEA,1,3,0,0,1,2,0,0,0,1.000000,202405,202405,1,9999,0
125623,2024-03-01,2024-03-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Pvea Comas,Cajas,Supervisor De Cajeros,Full Time,100754,Masculino,1994-07-02 00:00:00,29,2024-03-01,NaT,Indeterminado,No Aplicable,De 0 Mes - 1 Mes,1,0,1,1,30,De 0 a 30 días,Generación Y - [1980-2000],Operaciones - Tiendas,Anampa Montalvo,Sergio Jhenderson,1,0,0,1,Plaza Vea,Lima,Hiper,Vik Enciso,Sebastian Santangelo,Cajas,Supervisor De Cajeros,Medio,0.08333,Activos,No especifica,Plaza vea& Viv,2018-01-01 00:00:00,2026-05-01 00:00:00,101,Si,Pvea Comas,#ERROR,Cajas,NaN,1,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Cajero,Comas - PVH,30,Lima + Callao,C,PLAZA VEA,1,4,0,1,1,3,0,0,0,1.000000,202403,202403,1,9999,0
125627,2024-03-01,2024-03-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Pvea Colonial,Cajas,Supervisor De Cajeros,Full Time,10269607,Femenino,1999-11-12 00:00:00,24,2024-03-01,NaT,Indeterminado,No Aplicable,De 0 Mes - 1 Mes,1,0,1,1,30,De 0 a 30 días,Generación Y - [1980-2000],Operaciones - Tiendas,Mori Cumbia,Johana,1,0,0,1,Plaza Vea,Lima,Hiper,Vik Enciso,Sebastian Santangelo,Cajas,Supervisor De Cajeros,Medio,0.08333,Activos,No especifica,Plaza vea& Viv,2018-01-01 00:00:00,2026-05-01 00:00:00,101,Si,Pvea Colonial,#ERROR,Cajas,NaN,1,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Cajero,Colonial - PVH,30,Lima + Callao,B,PLAZA VEA,1,3,0,0,1,2,0,0,0,1.000000,202403,202403,1,9999,0
125646,2024-01-01,2024-01-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Pvea Brasil,Cajas,Supervisor De Cajeros,Full Time,6837581,Femenino,1997-07-11 00:00:00,26,2024-01-01,NaT,Indeterminado,No Aplicable,De 0 Mes - 1 Mes,1,0,1,1,30,De 0 a 30 días,Generación Y - [1980-2000],Operaciones - Tiendas,Anglas Quintanilla,Steffany Allison,1,0,0,1,Plaza Vea,Lima,Hiper,Vik Enciso,Sebastian Santangelo,Cajas,Supervisor De Cajeros,Medio,0.08333,Activos,No especifica,Plaza vea& Viv,2018-01-01 00:00:00,2026-05-01 00:00:00,101,Si,Pvea Brasil,#ERROR,Cajas,NaN,1,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Cajero,Brasil - PVH,30,Lima + Callao,B,PLAZA VEA,1,3,0,0,1,3,0,0,0,1.000000,202401,202401,1,9999,0
126789,2024-08-01,2024-08-31,Compañia Food Retail S.A.C.,Dir. Operaciones,Pvea Moquegua,Cajas,Cajero 6X1 2Do Turno,Part Time,5780418,Masculino,1995-02-12 00:00:00,29,2024-08-09,NaT,Part Time,Renuncia Voluntaria Por Cambio De Categoría,De 0 Mes - 1 Mes,1,0,1,1,22,De 0 a 30 días,Generación Y - [1980-2000],Operaciones - Tiendas,Perez Mamani,Joan Jesus,1,0,0,1,Plaza Vea,Provincia,Hiper,Joe Huamancondor,Sofia Villanueva,Cajas,Cajero 6X1,Operativo,0.06111,Activos,Involuntaria,Plaza vea& Viv,2018-01-01 00:00:00,2026-05-01 00:00:00,101,Si,Pvea Moquegua,#ERROR,Cajas,NaN,0.5,0,0.5,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Cajero,Moquegua - PVH,22,Provincia,B,PLAZA VEA,0,3,1,1,1,3,0,0,0,0.733333,202408,202408,1,9999,0

In [247]:
dff4.to_excel("revisa4.xlsx")

In [ ]:
df_prueba = dff4.groupby("Fecha inicio").agg(target = ("target_ff", "sum"), ingresos = ("target_ff", "count")).reset_index()
df_prueba["ratio"] = df_prueba["target"]/df_prueba["ingresos"]
df_prueba

   Fecha inicio  target  ingresos     ratio
0    2024-01-01      32       419  0.076372
1    2024-02-01      33       361  0.091413
2    2024-03-01      38       417  0.091127
3    2024-04-01      25       322  0.077640
4    2024-05-01      35       335  0.104478
5    2024-06-01       6       196  0.030612
6    2024-07-01       3       125  0.024000
7    2024-08-01      11       214  0.051402
8    2024-09-01      38       400  0.095000
9    2024-10-01      17       256  0.066406
10   2024-11-01      51      1018  0.050098
11   2024-12-01      72       276  0.260870
12   2025-01-01       1       100  0.010000
13   2025-02-01       6       169  0.035503
14   2025-03-01       7       218  0.032110
15   2025-04-01       5       249  0.020080
16   2025-05-01      19       290  0.065517
17   2025-06-01       7        77  0.090909
18   2025-07-01       6       149  0.040268
19   2025-08-01      10       205  0.048780
20   2025-09-01      22       358  0.061453
21   2025-10-01      28       319  0.087774
22   2025-11-01      26       408  0.063725
23   2025-12-01      79       840  0.094048
24   2026-01-01      16       194  0.082474
25   2026-02-01      11       234  0.047009
26   2026-03-01      19       312  0.060897
27   2026-04-01      30       324  0.092593
28   2026-05-01      29       316  0.091772

In [ ]:
dff3[dff3["flag_periodo_ingreso"]==1]

dff5= dff4[(dff4["flag_periodo_ingreso"]==1)&(dff4["formato"].isin(['PLAZA VEA', 'PLAZA VEA SUPER']))&(dff4["PuestoAgrupado"]=="Cajero")&(dff4["Fecha inicio"]>="2026-01-01")][["target_ff", "cat_edad", "cat_ubicacion", "cat_cluster", "cat_modalidad", "cat_genero"]]
dff5 = pd.get_dummies(
    dff5,
    columns=["cat_edad"],
    prefix="edad",
    dtype=int
)

# dff5 = pd.get_dummies(
#     dff5,
#     columns=["cat_cluster"],
#     prefix="cluster",
#     dtype=int
# )

In [ ]:
dff4[(dff4["flag_periodo_ingreso"]==1)&(dff4["formato"].isin(['PLAZA VEA', 'PLAZA VEA SUPER']))&(dff4["PuestoAgrupado"]=="Cajero")&(dff4["Fecha inicio"]>="2026-01-01")].groupby(["cat_edad"])["target_ff"].mean()

cat_edad
1    0.067086
2    0.099150
3    0.147059
4    0.089109
Name: target_ff, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score


X = dff5.drop(columns=['target_ff'])
y = dff5["target_ff"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

modelo = LogisticRegression(
    max_iter=1000,
    random_state=42,class_weight="balanced",
)

modelo.fit(X_train, y_train)


y_prob = modelo.predict_proba(X_test)[:, 1]

print("AUC:", roc_auc_score(y_test, y_prob))

AUC: 0.605277933745087

In [ ]:
import pandas as pd
import numpy as np

resultado = pd.DataFrame({
    "Variable": X.columns,
    "Coeficiente": modelo.coef_[0]
})

resultado["OddsRatio"] = np.exp(resultado["Coeficiente"])

resultado = resultado.sort_values(
    "OddsRatio",
    ascending=False
)

resultado

        Variable  Coeficiente  OddsRatio
2  cat_modalidad     0.771507   2.163023
6         edad_3     0.460078   1.584197
0  cat_ubicacion     0.330143   1.391167
5         edad_2     0.061010   1.062909
7         edad_4     0.029048   1.029474
1    cat_cluster     0.010384   1.010438
3     cat_genero    -0.286683   0.750750
4         edad_1    -0.549971   0.576967